### ISSUE TITLE
doesn't find th

### ISSUE THREAD

**Issue by tythompson85** [smasala/responsive-tables-js#1]
When going from desktop to responsive the script doesn't find the `th` so the column titles do not display.

**Comment by smasala** [comment]
What you mean desktop to responsive? How can reproduce this error? Are you simply switching modes using the chrome developer tools?

**Comment by tythompson85** [comment]
I am switching modes within the browser as well as also tried to horizontally make it trigger as well and it just simply doesn't find the tags.

**Comment by smasala** [comment]
What does your code look like?

**Comment by tythompson85** [comment]
I used to your exact example from git.

**Comment by smasala** [comment]
Please compare your code with the working example:

http://smasala.github.io/responsive-tables-js/demo.html

**Comment by tythompson85** [comment]
This is the exact same file I used in my code.

**Comment by smasala** [comment]
Are the url paths correct? It's difficult and doesn't make much sense for me to try and guess what's wrong if I can't see exactly what and how you've configured your system locally. Make a jsfiddle or plunkr similar please.

**Comment by tythompson85** [comment]
here is fiddle [Fiddle](https://jsfiddle.net/5jckhh8o/) as you can see whenever you are in mobile or less than 767px the titles no longer show.

**Comment by smasala** [comment]
Thanks for the jsfiddle.

You forgot to initialise the app:

```
$( document ).ready( function() {
	      window.responsiveTables.init();
	  } );
```
