### ISSUE TITLE
how i can apply for dynamically created table?

### ISSUE THREAD

**Issue by ipro-ollie** [smasala/responsive-tables-js#2]
hi, i am trying to apply this plugin for a dynamically created table, and getting nothing. how i can to fix it?

**Comment by smasala** [comment]
To init all tables just call `window.responsiveTables.init();`. Alternatively you can init specific tables by passing a selector `window.responsiveTables.init("#myTableId");`

**Comment by smasala** [comment]
Closed due to inactivity
