### ISSUE TITLE
Destroy or recreate

### ISSUE THREAD

**Issue by christiangrieger** [smasala/responsive-tables-js#3]
I try to use the script and it is working really well but i have problems with ajax content that is loaded.

I tried to just fire the function again but it looks like this does not work. Is there any way to reset the init and fire the function again?

**Comment by smasala** [comment]
@ChristianGrieger try calling the init function with the force flag `true` https://github.com/smasala/responsive-tables-js/blob/master/src/responsivetables.js#L43

**Comment by christiangrieger** [comment]
Thank you very much 👍
